function Get-Devices {
    <#
    .SYNOPSIS 
    Gets device data for all devices from the Datto RMM API

    .DESCRIPTION
    If provided with valid access parameters, this will return the device info available from the Datto RMM API

    .PARAMETER apiAccessToken
    API Access Token generated by New-DattoRmmApiAccessToken.

    .PARAMETER apiUrl
    Region-specific API Url. Allowable values are:

    https://pinotage-api.centrastage.net

    https://merlot-api.centrastage.net

    https://concord-api.centrastage.net

    https://zinfandel-api.centrastage.net

    https://syrah-api.centrastage.net

    .OUTPUTS
    [System.Object] custom object containing device data

    .EXAMPLE
    $devices = Get-Devices
    #>
    param
	(
        [parameter(Mandatory=$false)]
        [validateNotNullorEmpty()]
        [String]$apiAccessToken=$global:dattoRmmApiAccessToken,

        [parameter(Mandatory=$false)]
        [ValidateSet("https://pinotage-api.centrastage.net","https://merlot-api.centrastage.net","https://concord-api.centrastage.net","https://zinfandel-api.centrastage.net","https://syrah-api.centrastage.net")]
        [String]$apiUrl=$global:dattoRmmApiUrl

    )   
    $response = New-DattoRmmApiRequest -apiAccessToken $apiAccessToken -apiUrl $apiUrl -apiMethod "get" -apiRequest "account/devices"
    return $response
}